import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';

const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kotaui-test-'));
const port = 18108;
const subscriptionPort = 18109;
const proc = spawn(process.execPath, ['server/index.mjs'], { cwd: path.resolve(import.meta.dirname, '..'), env: { ...process.env, KOTAUI_DATA_DIR: dataDir, KOTAUI_PORT: String(port), KOTAUI_SUBSCRIPTION_PORT: String(subscriptionPort), KOTAUI_ADMIN_USER: 'admin', KOTAUI_ADMIN_PASSWORD: 'test-password' }, stdio: 'ignore' });
const base = `http://127.0.0.1:${port}`;
let cookie = '';
let inboundIds = [];
let clientId = '';
async function wait(){ for(let i=0;i<40;i++){ try { const r=await fetch(`${base}/api/health`); await r.text(); if(r.ok)return; } catch {} await new Promise(resolve=>setTimeout(resolve,100)); } throw Error('server did not start'); }
async function req(url, options={}){ const headers={'content-type':'application/json',...(cookie?{cookie}:{}),...(options.headers||{})}; const response=await fetch(base+url,{...options,headers,redirect:options.redirect||'follow'}); const text=await response.text(); let body={}; try{body=JSON.parse(text)}catch{body={text}} return { status:response.status, body, headers:response.headers }; }

test.before(async()=>{ await wait(); const login=await req('/api/auth/login',{method:'POST',body:JSON.stringify({username:'admin',password:'test-password'})}); assert.equal(login.status,200); cookie=login.headers.get('set-cookie').split(';')[0]; });
test.after(()=>{ proc.kill('SIGTERM'); fs.rmSync(dataDir,{recursive:true,force:true}); });

test('authentication protects state and system dashboard',async()=>{ const saved=cookie; cookie=''; assert.equal((await req('/api/state')).status,401); assert.equal((await req('/api/dashboard')).status,401); cookie=saved; const dashboard=await req('/api/dashboard'); assert.equal(dashboard.status,200); assert.ok(dashboard.body.metrics.memory.totalBytes>0); });
test('health and IP certificate warning',async()=>{ const x=await req('/api/health'); assert.equal(x.status,200); assert.equal(x.body.ok,true); const cert=await req('/api/certificates/preview',{method:'POST',body:JSON.stringify({domain:'203.0.113.10'})}); assert.equal(cert.body.isIp,true); assert.match(cert.body.warning,/有效期/); });
test('three supported inbound types and settings update',async()=>{ const reality=await req('/api/inbounds',{method:'POST',body:JSON.stringify({name:'reality-edge',type:'reality',port:18443,handshakeServer:'www.example.com',handshakePort:443,privateKey:'private-key',publicKey:'public-key',shortId:'0123456789abcdef'})}); assert.equal(reality.status,201); const hy2=await req('/api/inbounds',{method:'POST',body:JSON.stringify({name:'hy2-edge',type:'hysteria2',port:18444,tlsServerName:'example.com',upMbps:100,downMbps:500})}); assert.equal(hy2.status,201); const ss=await req('/api/inbounds',{method:'POST',body:JSON.stringify({name:'ss-edge',type:'shadowsocks2022',port:18445,network:'tcp,udp'})}); assert.equal(ss.status,201); inboundIds=[reality.body.id,hy2.body.id,ss.body.id]; const settings=await req('/api/settings',{method:'PUT',body:JSON.stringify({panelName:'KotaUI Test',titleEnabled:false,realityCandidates:[{host:'example.com',port:443}]})}); assert.equal(settings.body.panelName,'KotaUI Test'); assert.equal(settings.body.realityCandidates.length,1); });
test('client validation, lifecycle actions and dual subscription output',async()=>{ const invalid=await req('/api/clients',{method:'POST',body:JSON.stringify({username:'中文',inbounds:inboundIds})}); assert.equal(invalid.status,400); const missingInbound=await req('/api/clients',{method:'POST',body:JSON.stringify({username:'no_inbound'})}); assert.equal(missingInbound.status,400); const created=await req('/api/clients',{method:'POST',body:JSON.stringify({username:'alice_01',note:'测试',inbounds:inboundIds,totalLimitBytes:1024**3,monthlyLimitBytes:512*1024**2,maxOnlineIps:2})}); assert.equal(created.status,201); clientId=created.body.id; const browser=await req('/kota-sub/alice_01',{headers:{host:`example.com:${port}`}}); assert.equal(browser.status,200); assert.match(browser.body.text,/作者那么羡慕你/); const client=await req('/kota-sub/alice_01',{headers:{'user-agent':'v2rayNG',host:`example.com:${port}`}}); assert.equal(client.status,200); const decoded=Buffer.from(client.body.text,'base64').toString('utf8'); assert.match(decoded,/vless:\/\//); assert.match(decoded,/hysteria2:\/\//); assert.match(decoded,/ss:\/\//); const pause=await req(`/api/clients/${clientId}/action`,{method:'POST',body:JSON.stringify({action:'pause'})}); assert.equal(pause.status,200); assert.equal(pause.body.client.enabled,false); const denied=await req('/kota-sub/alice_01',{headers:{'user-agent':'v2rayNG'}}); assert.equal(denied.status,403); const resume=await req(`/api/clients/${clientId}/action`,{method:'POST',body:JSON.stringify({action:'resume'})}); assert.equal(resume.body.client.enabled,true); });
test('config generation and update rollback',async()=>{ const validation=await req('/api/config/validate',{method:'POST',body:'{}'}); assert.equal(validation.status,200); assert.ok(validation.body.configFile); const success=await req('/api/updates/run',{method:'POST',body:JSON.stringify({scope:'all',uiVersion:'9.9.9'})}); assert.equal(success.body.ok,true); assert.equal(success.body.versions.ui,'9.9.9'); const failed=await req('/api/updates/run',{method:'POST',body:JSON.stringify({scope:'all',uiVersion:'10.0.0',simulateFailure:true})}); assert.equal(failed.body.ok,false); assert.equal(failed.body.rolledBack,true); assert.equal(failed.body.versions.ui,'9.9.9'); });
