import http from 'node:http';
import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import net from 'node:net';
import tls from 'node:tls';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { hashPassword, verifyPassword, token } from './lib/security.mjs';
import { writeConfig, validateConfig, keyForMethod } from './lib/singbox.mjs';
import { certificateKind, certbotArgs, runCertbot, renewalCommand } from './lib/certs.mjs';
import { applyTraffic, activeIpDecision, markActiveIp, ensureMonthlyReset } from './lib/limits.mjs';
import { collectUserTraffic } from './lib/stats-client.mjs';
import { atomicReplace, backupFile, downloadArtifact } from './lib/updater.mjs';
import { openInboundPort, closeInboundPort } from './lib/firewall.mjs';
import { collectSystemMetrics, formatBytes, formatDuration } from './lib/system.mjs';
import { clientStatus, isSubscriptionClient, subscriptionHtml, subscriptionNotice, subscriptionPayload } from './lib/subscription.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = process.env.KOTAUI_DATA_DIR || path.join(root, 'data');
const adminEnvFile = process.env.KOTAUI_ADMIN_ENV || path.join(dataDir, 'admin.env');
if (!process.env.KOTAUI_ADMIN_USER && fs.existsSync(adminEnvFile)) { for (const line of fs.readFileSync(adminEnvFile, 'utf8').split(/\r?\n/)) { const match = line.match(/^([A-Z0-9_]+)=(.*)$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2]; } }
const configFile = process.env.KOTAUI_SINGBOX_CONFIG || path.join(dataDir, 'sing-box', 'config.json');
const port = Number(process.env.KOTAUI_PORT || 1108);
const tlsCert = process.env.KOTAUI_TLS_CERT || path.join(dataDir, 'certs', 'fullchain.pem');
const tlsKey = process.env.KOTAUI_TLS_KEY || path.join(dataDir, 'certs', 'privkey.pem');
const host = process.env.KOTAUI_HOST || (fs.existsSync(tlsCert) && fs.existsSync(tlsKey) ? '0.0.0.0' : '127.0.0.1');
const statsApiPort = Number(process.env.KOTAUI_STATS_PORT || 9090);
const subscriptionPort = Number(process.env.KOTAUI_SUBSCRIPTION_PORT || 1109);
const panelPath = `/${String(process.env.KOTAUI_PANEL_PATH || 'ptf').replace(/^\/+|\/+$/g, '')}`;
const panelDomain = String(process.env.KOTAUI_DOMAIN || '').trim();
const authRequired = process.env.KOTAUI_AUTH_DISABLED !== '1';
const managedServices = process.env.KOTAUI_MANAGE_SERVICES === '1';
fs.mkdirSync(dataDir, { recursive: true, mode: 0o700 });
const dbFile = path.join(dataDir, 'state.json');
const updateDir = path.join(dataDir, 'updates');
const supportedTypes = new Set(['reality', 'hysteria2', 'shadowsocks2022']);
const initialState = { settings: { panelName: 'KotaUI', domain: panelDomain, panelPort: port, panelPath, subscriptionPort, subscriptionPath: '/kota-sub', certFullchainPath: '/var/lib/kotaui/certs/fullchain.pem', certPrivateKeyPath: '/var/lib/kotaui/certs/privkey.pem', timeZone: 'UTC', titleEnabled: true, titleFields: ['username', 'used', 'total'], notice: subscriptionNotice(), realityCandidates: [{ host: 'www.cloudflare.com', port: 443 }, { host: 'www.microsoft.com', port: 443 }, { host: 'www.apple.com', port: 443 }] }, versions: { ui: '0.1.0', singBox: '1.13.18', lastUpdate: null }, auth: null, inbounds: [], clients: [], updateHistory: [], traffic: {} };
function clone(x) { return JSON.parse(JSON.stringify(x)); }
function save(next) { const tmp = `${dbFile}.tmp`; fs.writeFileSync(tmp, JSON.stringify(next, null, 2), { mode: 0o600 }); fs.renameSync(tmp, dbFile); }
function load() { try { const current = JSON.parse(fs.readFileSync(dbFile, 'utf8')); return { ...clone(initialState), ...current, settings: { ...initialState.settings, ...(current.settings || {}) }, versions: { ...initialState.versions, ...(current.versions || {}) } }; } catch { const fresh = clone(initialState); const username = process.env.KOTAUI_ADMIN_USER || 'admin'; const password = process.env.KOTAUI_ADMIN_PASSWORD || crypto.randomBytes(12).toString('base64url'); fresh.auth = { username, ...hashPassword(password), createdAt: new Date().toISOString() }; console.log(`KotaUI initial administrator: ${username}`); if (!process.env.KOTAUI_ADMIN_PASSWORD) console.log(`KotaUI initial password: ${password}`); save(fresh); return fresh; } }
let state = load();
const sessions = new Map();
const loginAttempts = new Map();
const send = (res, code, body, type='application/json', headers={}) => { res.writeHead(code, { 'Content-Type': `${type}; charset=utf-8`, 'Cache-Control': 'no-store', ...headers }); const payload = type === 'application/json' ? JSON.stringify(body) : (typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body)); res.end(payload); };
const readBody = req => new Promise((resolve, reject) => { let raw=''; let rejected = false; req.on('data', c => { if (rejected) return; raw += c; if (raw.length > 1_000_000) { rejected = true; req.destroy(); reject(new Error('request too large')); } }); req.on('end', () => { if (rejected) return; try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('invalid json')); } }); req.on('error', error => { if (!rejected) reject(error); }); });
const id = () => crypto.randomUUID();
const validUsername = name => typeof name === 'string' && /^[A-Za-z0-9_-]{3,32}$/.test(name);
const highPort = value => Number.isInteger(Number(value)) && Number(value) >= 1024 && Number(value) <= 65535;
function sessionFrom(req) { const raw = req.headers.cookie || ''; const match = raw.match(/kota_session=([a-f0-9]+)/); if (!match) return null; const session = sessions.get(match[1]); if (session && Date.now() - session.createdAt > 28_800_000) { sessions.delete(match[1]); return null; } return session || null; }
function protectedRoute(req, url) { return authRequired && !['/api/health', '/api/auth/status', '/api/auth/login', '/', panelPath, '/index.html'].includes(url.pathname) && !url.pathname.startsWith('/kota-sub/'); }
function validateInbound(b) { if (!b.name || !supportedTypes.has(b.type) || !highPort(b.port)) return '名称、支持的协议和 1024-65535 高位端口为必填项'; if (state.inbounds.some(x => Number(x.port) === Number(b.port) && x.id !== b.id)) return '节点端口已被其他入站占用'; if (b.type === 'reality' && (!b.handshakeServer || !b.privateKey || !b.publicKey || !b.shortId)) return 'VLESS + REALITY 需要目标域名、私钥、公钥和 short_id'; if (b.type === 'hysteria2' && !b.tlsServerName) return 'Hysteria 2 需要 TLS server_name'; if (b.type === 'shadowsocks2022' && b.method && b.method !== '2022-blake3-aes-256-gcm') return 'Shadowsocks 2022 首版固定使用 2022-blake3-aes-256-gcm'; return null; }
function restartSingBox() {
  if (!managedServices) return { attempted: false };
  const manager = fs.existsSync('/run/systemd/system') ? 'systemctl' : 'rc-service';
  const args = manager === 'systemctl' ? ['restart', 'kotaui-singbox.service'] : ['kotaui-singbox', 'restart'];
  const result = spawnSync(manager, args, { encoding: 'utf8', timeout: 30_000 });
  return { attempted: true, ok: !result.error && result.status === 0, error: result.error?.message || result.stderr?.trim() || '' };
}
function rebuildConfig({ restart = true } = {}) {
  const config = writeConfig(state, configFile, statsApiPort);
  const core = restart ? restartSingBox() : { attempted: false };
  if (core.attempted && !core.ok) throw new Error(`sing-box 配置已写入，但核心重启失败：${core.error || '未知错误'}`);
  return { config, core };
}
function normalizedInboundIds(ids) { return [...new Set((Array.isArray(ids) ? ids : []).filter(id => state.inbounds.some(inbound => inbound.id === id)))]; }
function clientSummary(client) { const status = clientStatus(client, state.settings.timeZone || 'UTC'); const total = Number(client.totalLimitBytes || 0); return { id: client.id, username: client.username, note: client.note || '', inbounds: client.inbounds || [], totalLimitBytes: total, monthlyLimitBytes: Number(client.monthlyLimitBytes || 0), usedBytes: Number(client.usedBytes || 0), monthlyUsedBytes: Number(client.monthlyUsedBytes || 0), expiresAt: client.expiresAt || null, maxOnlineIps: Number(client.maxOnlineIps || 0), enabled: status.enabled, state: status.reason, createdAt: client.createdAt, subscriptionPath: `${state.settings.subscriptionPath}/${encodeURIComponent(client.username)}` }; }
function certificateStatus() { const cert = state.settings.certFullchainPath || tlsCert; if (!fs.existsSync(cert)) return { present: false }; const result = spawnSync('openssl', ['x509', '-enddate', '-noout', '-in', cert], { encoding: 'utf8', timeout: 5_000 }); const value = String(result.stdout || '').trim().replace(/^notAfter=/, ''); const expiresAt = value ? new Date(value).toISOString() : null; return { present: result.status === 0, expiresAt, source: cert }; }
function dashboard() { const metrics = collectSystemMetrics(); const clients = state.clients.map(clientSummary); return { metrics, certificate: certificateStatus(), versions: state.versions, inbounds: { total: state.inbounds.length, enabled: state.inbounds.filter(inbound => inbound.enabled !== false).length }, clients: { total: clients.length, enabled: clients.filter(client => client.enabled).length, paused: clients.filter(client => !client.enabled).length }, traffic: { usedBytes: clients.reduce((sum, client) => sum + Number(client.usedBytes || 0), 0), monthlyUsedBytes: clients.reduce((sum, client) => sum + Number(client.monthlyUsedBytes || 0), 0), usedLabel: formatBytes(clients.reduce((sum, client) => sum + Number(client.usedBytes || 0), 0)), uptimeLabel: formatDuration(metrics.uptimeSeconds) } }; }
function probeRealityTarget(hostname, targetPort = 443) { return new Promise(resolve => { const started = Date.now(); const socket = tls.connect({ host: hostname, port: Number(targetPort), servername: hostname, minVersion: 'TLSv1.2', rejectUnauthorized: false, ALPNProtocols: ['h2', 'http/1.1'] }); const finish = value => { socket.destroy(); resolve(value); }; socket.setTimeout(7_000, () => finish({ ok: false, host: hostname, port: Number(targetPort), error: '连接超时' })); socket.once('error', error => finish({ ok: false, host: hostname, port: Number(targetPort), error: error.message })); socket.once('secureConnect', () => { const cert = socket.getPeerCertificate(); finish({ ok: true, host: hostname, port: Number(targetPort), latencyMs: Date.now() - started, tlsVersion: socket.getProtocol(), alpn: socket.alpnProtocol || '', serverNames: String(cert.subjectaltname || '').split(',').map(item => item.trim().replace(/^DNS:/, '')).filter(Boolean).slice(0, 12), issuer: cert.issuer?.O || cert.issuer?.CN || '', expiresAt: cert.valid_to ? new Date(cert.valid_to).toISOString() : null }); }); }); }
function generateRealityKeyPair() { const binary = process.env.SING_BOX_BINARY || 'sing-box'; const result = spawnSync(binary, ['generate', 'reality-keypair'], { encoding: 'utf8', timeout: 10_000 }); if (result.error || result.status !== 0) throw new Error('无法生成 REALITY 密钥对；请确认 sing-box 已安装。'); const text = `${result.stdout || ''}${result.stderr || ''}`; const privateKey = (text.match(/PrivateKey:\s*(\S+)/i) || [])[1]; const publicKey = (text.match(/PublicKey:\s*(\S+)/i) || [])[1]; if (!privateKey || !publicKey) throw new Error('sing-box 返回的 REALITY 密钥格式无法识别。'); return { privateKey, publicKey }; }
function certPreview(value) { const kind = certificateKind(value); return { input: kind.subject, isIp: kind.isIp, warning: kind.warning, recommended: kind.isIp ? '确认 CA 支持 IP 证书，并启用高频续期和到期提醒。' : '可使用标准 ACME 域名验证流程。' }; }
function createBackup() { fs.mkdirSync(updateDir, { recursive: true, mode: 0o700 }); const file = path.join(updateDir, `backup-${Date.now()}.json`); fs.writeFileSync(file, JSON.stringify(state, null, 2), { mode: 0o600 }); return file; }
async function applyArtifacts(artifacts = []) { const applied = []; for (const artifact of artifacts) { const source = artifact.path || path.join(updateDir, `${artifact.name}.download`); if (artifact.url) await downloadArtifact(artifact.url, source, ['github.com', 'objects.githubusercontent.com', 'raw.githubusercontent.com']); if (!fs.existsSync(source)) throw new Error(`更新文件不存在: ${artifact.name || source}`); const backup = backupFile(artifact.destination, updateDir); atomicReplace(source, artifact.destination, artifact.sha256); applied.push({ name: artifact.name || path.basename(artifact.destination), destination: artifact.destination, backup }); } return applied; }
async function runUpdate(body) { const backupFile = createBackup(); const before = clone(state); const selected = body.scope || 'all'; const update = { id: id(), scope: selected, startedAt: new Date().toISOString(), status: 'running', backupFile }; let appliedArtifacts = []; state.updateHistory.unshift(update); save(state); try { if (body.simulateFailure) throw new Error('模拟更新失败'); if (selected === 'all' || selected === 'ui') state.versions.ui = body.uiVersion || '0.1.1'; if (selected === 'all' || selected === 'sing-box') state.versions.singBox = body.singBoxVersion || '1.14.1'; appliedArtifacts = await applyArtifacts(body.artifacts || []); rebuildConfig(); state.versions.lastUpdate = new Date().toISOString(); update.status = 'success'; update.finishedAt = new Date().toISOString(); save(state); return { ok: true, update: { ...update, appliedArtifacts }, versions: state.versions }; } catch (error) { for (const artifact of appliedArtifacts) { if (artifact.backup && fs.existsSync(artifact.backup)) { fs.copyFileSync(artifact.backup, artifact.destination); fs.chmodSync(artifact.destination, 0o700); } } state = before; state.updateHistory.unshift({ ...update, status: 'rolled_back', appliedArtifacts, error: error.message, finishedAt: new Date().toISOString() }); save(state); return { ok: false, rolledBack: true, error: error.message, versions: state.versions }; } }
const routes = async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  if (req.method === 'GET' && url.pathname === '/api/health') return send(res, 200, { ok: true, service: 'kotaui', version: state.versions.ui, uptime: process.uptime(), panelPath: state.settings.panelPath, coreManaged: managedServices });
  if (req.method === 'GET' && url.pathname === '/api/dashboard') { if (authRequired && !sessionFrom(req)) return send(res, 401, { error: '需要管理员登录' }); return send(res, 200, dashboard()); }
  if (req.method === 'GET' && url.pathname === '/api/auth/status') return send(res, 200, { authenticated: Boolean(sessionFrom(req)), required: authRequired, username: state.auth?.username || null });
  if (req.method === 'POST' && url.pathname === '/api/auth/login') { const b = await readBody(req); const ip = req.socket.remoteAddress || 'unknown'; const attempts = (loginAttempts.get(ip) || []).filter(x => Date.now() - x < 300000); if (attempts.length >= 5) return send(res, 429, { error: '登录失败次数过多，请稍后再试' }); if (!state.auth || b.username !== state.auth.username || !verifyPassword(b.password, state.auth)) { attempts.push(Date.now()); loginAttempts.set(ip, attempts); return send(res, 401, { error: '用户名或密码错误' }); } loginAttempts.delete(ip); const key = token(); sessions.set(key, { username: b.username, createdAt: Date.now() }); const secure = fs.existsSync(tlsCert) && fs.existsSync(tlsKey) ? '; Secure' : ''; return send(res, 200, { ok: true }, 'application/json', { 'Set-Cookie': `kota_session=${key}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${secure}` }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/logout') { const session = sessionFrom(req); if (session) { const key = (req.headers.cookie.match(/kota_session=([a-f0-9]+)/) || [])[1]; sessions.delete(key); } return send(res, 200, { ok: true }, 'application/json', { 'Set-Cookie': 'kota_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0' }); }
  if (protectedRoute(req, url) && !sessionFrom(req)) return send(res, 401, { error: '需要管理员登录' });
  if (req.method === 'GET' && url.pathname === '/api/state') return send(res, 200, { settings: state.settings, versions: state.versions, inbounds: state.inbounds.map(x => ({ ...x, config: undefined, privateKey: undefined, password: undefined })), clients: state.clients.map(clientSummary), traffic: state.traffic });
  if (req.method === 'GET' && url.pathname === '/api/settings') return send(res, 200, state.settings);
  if (req.method === 'PUT' && url.pathname === '/api/settings') { const body = await readBody(req); const allowed = ['panelName', 'timeZone', 'titleEnabled', 'titleFields', 'notice', 'realityCandidates']; const next = Object.fromEntries(Object.entries(body).filter(([key]) => allowed.includes(key))); if (next.realityCandidates && (!Array.isArray(next.realityCandidates) || next.realityCandidates.length > 20)) return send(res, 400, { error: 'REALITY 候选必须为不超过 20 项的列表' }); state.settings = { ...state.settings, ...next }; save(state); return send(res, 200, state.settings); }
  if (req.method === 'POST' && url.pathname === '/api/certificates/preview') { const b = await readBody(req); return send(res, 200, { ...certPreview(b.domain), certbot: certbotArgs({ subject: b.domain, email: b.email, webroot: b.webroot, staging: Boolean(b.staging) }) }); }
  if (req.method === 'POST' && url.pathname === '/api/certificates/issue') { const b = await readBody(req); return send(res, 200, runCertbot({ subject: b.domain, email: b.email, webroot: b.webroot, staging: Boolean(b.staging) }, process.env.CERTBOT_BINARY || 'certbot')); }
  if (req.method === 'POST' && url.pathname === '/api/certificates/renew') return send(res, 200, { command: renewalCommand(process.env.CERTBOT_BINARY || 'certbot', process.env.KOTAUI_RENEW_HOOK || ''), certificate: certificateStatus() });
  if (req.method === 'GET' && url.pathname === '/api/reality/candidates') return send(res, 200, { candidates: state.settings.realityCandidates || [] });
  if (req.method === 'POST' && url.pathname === '/api/reality/probe') { const body = await readBody(req); const hostname = String(body.host || '').trim(); const targetPort = Number(body.port || 443); if (!hostname || !highPort(targetPort)) return send(res, 400, { error: '请提供有效的目标主机与端口' }); return send(res, 200, await probeRealityTarget(hostname, targetPort)); }
  if (req.method === 'POST' && url.pathname === '/api/reality/keypair') return send(res, 200, generateRealityKeyPair());
  if (req.method === 'POST' && url.pathname === '/api/traffic/sync') { const b = await readBody(req); const values = await collectUserTraffic(b.address || `127.0.0.1:${statsApiPort}`, state.clients.map(x => x.username)); let configChanged = false; for (const client of state.clients) { const item = values[client.username]; if (!item) continue; const previous = state.traffic[client.username]?.singbox || { uploadBytes: 0, downloadBytes: 0 }; const wasEnabled = client.enabled !== false; const uploadDelta = Math.max(0, item.uploadBytes - previous.uploadBytes); const downloadDelta = Math.max(0, item.downloadBytes - previous.downloadBytes); ensureMonthlyReset(client, state.settings.timeZone || 'UTC'); applyTraffic(client, uploadDelta, downloadDelta, state.settings.timeZone || 'UTC'); if (wasEnabled !== (client.enabled !== false)) configChanged = true; state.traffic[client.username] = { ...(state.traffic[client.username] || {}), singbox: item, usedBytes: client.usedBytes, monthlyUsedBytes: client.monthlyUsedBytes, updatedAt: new Date().toISOString() }; } save(state); if (configChanged) rebuildConfig(); return send(res, 200, { ok: true, traffic: state.traffic, coreReloaded: configChanged }); }
  if (req.method === 'POST' && url.pathname === '/api/traffic/apply') { const b = await readBody(req); const client = state.clients.find(x => x.id === b.clientId || x.username === b.username); if (!client) return send(res, 404, { error: 'client not found' }); const wasEnabled = client.enabled !== false; ensureMonthlyReset(client, state.settings.timeZone || 'UTC'); applyTraffic(client, b.uploadBytes, b.downloadBytes, state.settings.timeZone || 'UTC'); state.traffic[client.username] = { ...(state.traffic[client.username] || {}), usedBytes: client.usedBytes, monthlyUsedBytes: client.monthlyUsedBytes, updatedAt: new Date().toISOString() }; save(state); if (wasEnabled !== (client.enabled !== false)) rebuildConfig(); return send(res, 200, { client: clientSummary(client), traffic: state.traffic[client.username] }); }
  if (req.method === 'POST' && url.pathname === '/api/traffic/online') { const b = await readBody(req); const client = state.clients.find(x => x.id === b.clientId || x.username === b.username); if (!client) return send(res, 404, { error: 'client not found' }); const current = state.traffic[client.username]?.activeIps || {}; const next = markActiveIp(current, b.ip); const decision = activeIpDecision(client, next); state.traffic[client.username] = { ...(state.traffic[client.username] || {}), activeIps: next, activeIpCount: decision.activeIps.length, lastOnlineCheck: new Date().toISOString() }; save(state); return send(res, decision.allowed ? 200 : 429, { ...decision, clientEnabled: client.enabled !== false }); }
  if (req.method === 'GET' && url.pathname === '/api/updates') return send(res, 200, { current: state.versions, available: { ui: '0.1.1', singBox: '1.13.18' }, history: state.updateHistory.slice(0, 10) });
  if (req.method === 'POST' && url.pathname === '/api/updates/run') return send(res, 200, await runUpdate(await readBody(req)));
  if (req.method === 'POST' && url.pathname === '/api/config/validate') { rebuildConfig(); return send(res, 200, { configFile, ...validateConfig(configFile, process.env.SING_BOX_BINARY || 'sing-box') }); }
  if (req.method === 'POST' && url.pathname === '/api/inbounds') { const b = await readBody(req); const prepared = { ...b, method: b.type === 'shadowsocks2022' ? '2022-blake3-aes-256-gcm' : b.method }; const error = validateInbound(prepared); if (error) return send(res, 400, { error }); const item = { ...prepared, id: id(), name: String(prepared.name).trim(), port: Number(prepared.port), listen: prepared.listen || '0.0.0.0', network: prepared.type === 'shadowsocks2022' ? (prepared.network || 'tcp,udp') : prepared.network, password: prepared.type === 'shadowsocks2022' ? (prepared.password || keyForMethod(prepared.method)) : prepared.password, enabled: prepared.enabled !== false, createdAt: new Date().toISOString() }; state.inbounds.push(item); const core = rebuildConfig(); save(state); const firewall = openInboundPort(item.port, item.type === 'hysteria2' ? 'udp' : item.type === 'shadowsocks2022' ? item.network : 'tcp'); return send(res, 201, { ...item, privateKey: undefined, password: undefined, firewall, core }); }
  if (req.method === 'DELETE' && url.pathname.startsWith('/api/inbounds/')) { const iid = url.pathname.split('/').pop(); const removed = state.inbounds.find(x => x.id === iid); const before = state.inbounds.length; state.inbounds = state.inbounds.filter(x => x.id !== iid); if (before === state.inbounds.length) return send(res, 404, { error: 'inbound not found' }); state.clients.forEach(c => c.inbounds = c.inbounds.filter(x => x !== iid)); rebuildConfig(); save(state); const firewall = closeInboundPort(removed.port, removed.type === 'hysteria2' ? 'udp' : removed.type === 'shadowsocks2022' ? removed.network : 'tcp'); return send(res, 200, { ok: true, firewall }); }
  if (req.method === 'POST' && url.pathname === '/api/clients') { const b = await readBody(req); const username = String(b.username || '').trim(); const inbounds = normalizedInboundIds(b.inbounds); if (!validUsername(username)) return send(res, 400, { error: '用户名必须为 3-32 位字母、数字、下划线或连字符' }); if (state.clients.some(client => client.username === username)) return send(res, 409, { error: '用户名已存在' }); if (!inbounds.length) return send(res, 400, { error: '请至少选择一个已创建入站' }); const totalLimitBytes = Math.max(0, Number(b.totalLimitBytes || 0)); const monthlyLimitBytes = Math.max(0, Number(b.monthlyLimitBytes || 0)); const maxOnlineIps = Math.max(0, Math.floor(Number(b.maxOnlineIps || 0))); const item = { id: id(), username, note: String(b.note || '').slice(0, 120), inbounds, totalLimitBytes, monthlyLimitBytes, expiresAt: b.expiresAt ? new Date(b.expiresAt).toISOString() : null, maxOnlineIps, enabled: true, usedBytes: 0, monthlyUsedBytes: 0, credentials: { reality: crypto.randomUUID(), hysteria2: crypto.randomBytes(18).toString('base64url'), shadowsocks2022: keyForMethod('2022-blake3-aes-256-gcm') }, createdAt: new Date().toISOString() }; if (item.expiresAt && Number.isNaN(new Date(item.expiresAt).getTime())) return send(res, 400, { error: '有效期格式无效' }); state.clients.push(item); const core = rebuildConfig(); save(state); return send(res, 201, { ...clientSummary(item), core }); }
  if (req.method === 'PATCH' && url.pathname.startsWith('/api/clients/')) { const cid = url.pathname.split('/').pop(); const item = state.clients.find(client => client.id === cid); if (!item) return send(res, 404, { error: '客户端不存在' }); const b = await readBody(req); if (b.username && (!validUsername(String(b.username)) || state.clients.some(client => client.id !== cid && client.username === b.username))) return send(res, 400, { error: '用户名无效或已存在' }); if (b.inbounds) { const ids = normalizedInboundIds(b.inbounds); if (!ids.length) return send(res, 400, { error: '请至少选择一个已创建入站' }); item.inbounds = ids; } for (const field of ['username', 'note', 'totalLimitBytes', 'monthlyLimitBytes', 'expiresAt', 'maxOnlineIps']) if (Object.hasOwn(b, field)) item[field] = b[field]; item.note = String(item.note || '').slice(0, 120); item.totalLimitBytes = Math.max(0, Number(item.totalLimitBytes || 0)); item.monthlyLimitBytes = Math.max(0, Number(item.monthlyLimitBytes || 0)); item.maxOnlineIps = Math.max(0, Math.floor(Number(item.maxOnlineIps || 0))); if (item.expiresAt) { const parsed = new Date(item.expiresAt); if (Number.isNaN(parsed.getTime())) return send(res, 400, { error: '有效期格式无效' }); item.expiresAt = parsed.toISOString(); } const core = rebuildConfig(); save(state); return send(res, 200, { ...clientSummary(item), core }); }
  if (req.method === 'POST' && url.pathname.match(/^\/api\/clients\/[^/]+\/action$/)) { const cid = url.pathname.split('/')[3]; const item = state.clients.find(client => client.id === cid); if (!item) return send(res, 404, { error: '客户端不存在' }); const body = await readBody(req); const action = String(body.action || ''); if (action === 'pause') item.enabled = false; else if (action === 'resume') item.enabled = true; else if (action === 'reset') { item.usedBytes = 0; item.monthlyUsedBytes = 0; item.monthKey = undefined; } else if (action === 'regenerate') item.credentials = { reality: crypto.randomUUID(), hysteria2: crypto.randomBytes(18).toString('base64url'), shadowsocks2022: keyForMethod('2022-blake3-aes-256-gcm') }; else if (action === 'delete') { state.clients = state.clients.filter(client => client.id !== cid); delete state.traffic[item.username]; const core = rebuildConfig(); save(state); return send(res, 200, { ok: true, deleted: cid, core }); } else return send(res, 400, { error: '不支持的客户端操作' }); const core = rebuildConfig(); save(state); return send(res, 200, { ok: true, client: clientSummary(item), core }); }
  if (req.method === 'GET' && url.pathname.startsWith(`${state.settings.subscriptionPath}/`)) { const username = decodeURIComponent(url.pathname.slice(`${state.settings.subscriptionPath}/`.length)); const client = state.clients.find(item => item.username === username); if (!client) return send(res, 404, { error: 'subscription not found' }, 'text/plain'); const status = clientStatus(client, state.settings.timeZone || 'UTC'); const requestHost = new URL(`https://${req.headers.host || state.settings.domain}`).hostname; if (isSubscriptionClient(req.headers['user-agent'] || '', url.search)) { const payload = subscriptionPayload(state, client, requestHost); return send(res, status.enabled ? 200 : 403, payload.body, 'text/plain', payload.headers); } return send(res, status.enabled ? 200 : 403, subscriptionHtml(state, client, requestHost), 'text/html'); }
  if (req.method === 'GET' && url.pathname === '/') { res.writeHead(302, { Location: state.settings.panelPath, 'Cache-Control': 'no-store' }); return res.end(); }
  if (req.method === 'GET' && (url.pathname === state.settings.panelPath || url.pathname === '/index.html')) return send(res, 200, fs.readFileSync(path.join(root, 'public', 'index.html'), 'utf8'), 'text/html');
  return send(res, 404, { error: 'not found' });
};
const handler = (req, res) => routes(req, res).catch(err => send(res, 400, { error: err.message }));
const subscriptionHandler = (req, res) => { const url = new URL(req.url, `https://${req.headers.host || 'localhost'}`); if (!url.pathname.startsWith(`${state.settings.subscriptionPath}/`)) return send(res, 404, { error: 'not found' }); return routes(req, res).catch(err => send(res, 400, { error: err.message })); };
const tlsOptions = fs.existsSync(tlsCert) && fs.existsSync(tlsKey) ? { cert: fs.readFileSync(tlsCert), key: fs.readFileSync(tlsKey), minVersion: 'TLSv1.2' } : null;
const createPublicServer = routeHandler => tlsOptions ? https.createServer(tlsOptions, routeHandler) : http.createServer(routeHandler);
const server = createPublicServer(handler);
const subscriptionServer = subscriptionPort === port ? null : createPublicServer(subscriptionHandler);
for (const activeServer of [server, subscriptionServer].filter(Boolean)) { activeServer.keepAliveTimeout = 5_000; activeServer.headersTimeout = 10_000; activeServer.requestTimeout = 30_000; activeServer.maxConnections = Number(process.env.KOTAUI_MAX_CONNECTIONS || 256); }
server.listen(port, host, () => { try { rebuildConfig({ restart: false }); } catch (error) { console.error(`config initialization failed: ${error.message}`); } console.log(`KotaUI panel listening on ${tlsOptions ? 'https' : 'http'}://${host}:${port}${state.settings.panelPath}`); });
if (subscriptionServer) subscriptionServer.listen(subscriptionPort, host, () => console.log(`KotaUI subscription listening on ${tlsOptions ? 'https' : 'http'}://${host}:${subscriptionPort}${state.settings.subscriptionPath}`));
