import http from 'node:http';
import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import net from 'node:net';
import { fileURLToPath } from 'node:url';
import { hashPassword, verifyPassword, token } from './lib/security.mjs';
import { writeConfig, validateConfig } from './lib/singbox.mjs';
import { certificateKind, certbotArgs, runCertbot, renewalCommand } from './lib/certs.mjs';
import { applyTraffic, activeIpDecision, markActiveIp, ensureMonthlyReset } from './lib/limits.mjs';
import { collectUserTraffic } from './lib/stats-client.mjs';
import { atomicReplace, backupFile, downloadArtifact } from './lib/updater.mjs';
import { openInboundPort, closeInboundPort } from './lib/firewall.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = process.env.KOTAUI_DATA_DIR || path.join(root, 'data');
const configFile = process.env.KOTAUI_SINGBOX_CONFIG || path.join(dataDir, 'sing-box', 'config.json');
const port = Number(process.env.KOTAUI_PORT || 1108);
const tlsCert = process.env.KOTAUI_TLS_CERT || path.join(dataDir, 'certs', 'fullchain.pem');
const tlsKey = process.env.KOTAUI_TLS_KEY || path.join(dataDir, 'certs', 'privkey.pem');
const host = process.env.KOTAUI_HOST || '127.0.0.1';
const statsApiPort = Number(process.env.KOTAUI_STATS_PORT || 9090);
const authRequired = process.env.KOTAUI_AUTH_DISABLED !== '1';
fs.mkdirSync(dataDir, { recursive: true, mode: 0o700 });
const dbFile = path.join(dataDir, 'state.json');
const updateDir = path.join(dataDir, 'updates');
const supportedTypes = new Set(['reality', 'hysteria2', 'shadowsocks2022']);
const initialState = { settings: { panelName: 'KotaUI', domain: '', panelPort: port, panelPath: '/admin', subscriptionPort: 1109, subscriptionPath: '/kota-sub', certFullchainPath: '/var/lib/kotaui/certs/fullchain.pem', certPrivateKeyPath: '/var/lib/kotaui/certs/privkey.pem', timeZone: 'UTC', titleEnabled: true, titleFields: ['username', 'used', 'total'] }, versions: { ui: '0.1.0', singBox: '1.14.0', hysteria2: '2.6.0', lastUpdate: null }, auth: null, inbounds: [], clients: [], updateHistory: [], traffic: {} };
function clone(x) { return JSON.parse(JSON.stringify(x)); }
function save(next) { const tmp = `${dbFile}.tmp`; fs.writeFileSync(tmp, JSON.stringify(next, null, 2), { mode: 0o600 }); fs.renameSync(tmp, dbFile); }
function load() { try { const current = JSON.parse(fs.readFileSync(dbFile, 'utf8')); return { ...clone(initialState), ...current, settings: { ...initialState.settings, ...(current.settings || {}) }, versions: { ...initialState.versions, ...(current.versions || {}) } }; } catch { const fresh = clone(initialState); const username = process.env.KOTAUI_ADMIN_USER || 'admin'; const password = process.env.KOTAUI_ADMIN_PASSWORD || crypto.randomBytes(12).toString('base64url'); fresh.auth = { username, ...hashPassword(password), createdAt: new Date().toISOString() }; console.log(`KotaUI initial administrator: ${username}`); if (!process.env.KOTAUI_ADMIN_PASSWORD) console.log(`KotaUI initial password: ${password}`); save(fresh); return fresh; } }
let state = load();
const sessions = new Map();
const loginAttempts = new Map();
const send = (res, code, body, type='application/json', headers={}) => { res.writeHead(code, { 'Content-Type': `${type}; charset=utf-8`, 'Cache-Control': 'no-store', ...headers }); const payload = type === 'application/json' ? JSON.stringify(body) : (typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body)); res.end(payload); };
const readBody = req => new Promise((resolve, reject) => { let raw=''; req.on('data', c => { raw += c; if (raw.length > 1_000_000) reject(new Error('request too large')); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('invalid json')); } }); req.on('error', reject); });
const id = () => crypto.randomUUID();
const validUsername = name => typeof name === 'string' && /^[A-Za-z0-9_-]{3,32}$/.test(name);
const highPort = value => Number.isInteger(Number(value)) && Number(value) >= 1024 && Number(value) <= 65535;
function sessionFrom(req) { const raw = req.headers.cookie || ''; const match = raw.match(/kota_session=([a-f0-9]+)/); return match ? sessions.get(match[1]) : null; }
function protectedRoute(req, url) { return authRequired && !['/api/health', '/api/auth/status', '/api/auth/login', '/'].includes(url.pathname) && !url.pathname.startsWith('/kota-sub/'); }
function validateInbound(b) { if (!b.name || !supportedTypes.has(b.type) || !highPort(b.port)) return '名称、支持的协议和 1024-65535 高位端口为必填项'; if (state.inbounds.some(x => Number(x.port) === Number(b.port) && x.id !== b.id)) return '节点端口已被其他入站占用'; if (b.type === 'reality' && (!b.handshakeServer || !b.privateKey || !b.shortId)) return 'Reality 需要握手域名、私钥和 short_id'; if (b.type === 'hysteria2' && !b.tlsServerName) return 'Hysteria 2 需要 TLS server_name'; if (b.type === 'shadowsocks2022' && !['2022-blake3-aes-128-gcm', '2022-blake3-aes-256-gcm', '2022-blake3-chacha20-poly1305'].includes(b.method)) return 'Shadowsocks 2022 加密方法无效'; return null; }
function rebuildConfig() { return writeConfig(state, configFile, statsApiPort); }
function certPreview(value) { const kind = certificateKind(value); return { input: kind.subject, isIp: kind.isIp, warning: kind.warning, recommended: kind.isIp ? '确认 CA 支持 IP 证书，并启用高频续期和到期提醒。' : '可使用标准 ACME 域名验证流程。' }; }
function createBackup() { fs.mkdirSync(updateDir, { recursive: true, mode: 0o700 }); const file = path.join(updateDir, `backup-${Date.now()}.json`); fs.writeFileSync(file, JSON.stringify(state, null, 2), { mode: 0o600 }); return file; }
async function applyArtifacts(artifacts = []) { const applied = []; for (const artifact of artifacts) { const source = artifact.path || path.join(updateDir, `${artifact.name}.download`); if (artifact.url) await downloadArtifact(artifact.url, source, ['github.com', 'objects.githubusercontent.com', 'raw.githubusercontent.com']); if (!fs.existsSync(source)) throw new Error(`更新文件不存在: ${artifact.name || source}`); const backup = backupFile(artifact.destination, updateDir); atomicReplace(source, artifact.destination, artifact.sha256); applied.push({ name: artifact.name || path.basename(artifact.destination), destination: artifact.destination, backup }); } return applied; }
async function runUpdate(body) { const backupFile = createBackup(); const before = clone(state); const selected = body.scope || 'all'; const update = { id: id(), scope: selected, startedAt: new Date().toISOString(), status: 'running', backupFile }; let appliedArtifacts = []; state.updateHistory.unshift(update); save(state); try { if (body.simulateFailure) throw new Error('模拟更新失败'); if (selected === 'all' || selected === 'ui') state.versions.ui = body.uiVersion || '0.1.1'; if (selected === 'all' || selected === 'sing-box') state.versions.singBox = body.singBoxVersion || '1.14.1'; if (selected === 'all' || selected === 'hysteria2') state.versions.hysteria2 = body.hysteria2Version || '2.6.1'; appliedArtifacts = await applyArtifacts(body.artifacts || []); rebuildConfig(); state.versions.lastUpdate = new Date().toISOString(); update.status = 'success'; update.finishedAt = new Date().toISOString(); save(state); return { ok: true, update: { ...update, appliedArtifacts }, versions: state.versions }; } catch (error) { for (const artifact of appliedArtifacts) { if (artifact.backup && fs.existsSync(artifact.backup)) { fs.copyFileSync(artifact.backup, artifact.destination); fs.chmodSync(artifact.destination, 0o700); } } state = before; state.updateHistory.unshift({ ...update, status: 'rolled_back', appliedArtifacts, error: error.message, finishedAt: new Date().toISOString() }); save(state); return { ok: false, rolledBack: true, error: error.message, versions: state.versions }; } }
const routes = async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  if (req.method === 'GET' && url.pathname === '/api/health') return send(res, 200, { ok: true, service: 'kotaui', version: state.versions.ui, uptime: process.uptime() });
  if (req.method === 'GET' && url.pathname === '/api/auth/status') return send(res, 200, { authenticated: Boolean(sessionFrom(req)), required: authRequired, username: state.auth?.username || null });
  if (req.method === 'POST' && url.pathname === '/api/auth/login') { const b = await readBody(req); const ip = req.socket.remoteAddress || 'unknown'; const attempts = (loginAttempts.get(ip) || []).filter(x => Date.now() - x < 300000); if (attempts.length >= 5) return send(res, 429, { error: '登录失败次数过多，请稍后再试' }); if (!state.auth || b.username !== state.auth.username || !verifyPassword(b.password, state.auth)) { attempts.push(Date.now()); loginAttempts.set(ip, attempts); return send(res, 401, { error: '用户名或密码错误' }); } loginAttempts.delete(ip); const key = token(); sessions.set(key, { username: b.username, createdAt: Date.now() }); const secure = fs.existsSync(tlsCert) && fs.existsSync(tlsKey) ? '; Secure' : ''; return send(res, 200, { ok: true }, 'application/json', { 'Set-Cookie': `kota_session=${key}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${secure}` }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/logout') { const session = sessionFrom(req); if (session) { const key = (req.headers.cookie.match(/kota_session=([a-f0-9]+)/) || [])[1]; sessions.delete(key); } return send(res, 200, { ok: true }, 'application/json', { 'Set-Cookie': 'kota_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0' }); }
  if (protectedRoute(req, url) && !sessionFrom(req)) return send(res, 401, { error: '需要管理员登录' });
  if (req.method === 'GET' && url.pathname === '/api/state') return send(res, 200, { settings: state.settings, versions: state.versions, inbounds: state.inbounds.map(x => ({ ...x, config: undefined, privateKey: undefined, password: undefined })), clients: state.clients.map(c => ({ ...c, password: undefined, credentials: undefined })), traffic: state.traffic });
  if (req.method === 'GET' && url.pathname === '/api/settings') return send(res, 200, state.settings);
  if (req.method === 'PUT' && url.pathname === '/api/settings') { const body = await readBody(req); state.settings = { ...state.settings, ...body }; save(state); return send(res, 200, state.settings); }
  if (req.method === 'POST' && url.pathname === '/api/certificates/preview') { const b = await readBody(req); return send(res, 200, { ...certPreview(b.domain), certbot: certbotArgs({ subject: b.domain, email: b.email, webroot: b.webroot, staging: Boolean(b.staging) }) }); }
  if (req.method === 'POST' && url.pathname === '/api/certificates/issue') { const b = await readBody(req); return send(res, 200, runCertbot({ subject: b.domain, email: b.email, webroot: b.webroot, staging: Boolean(b.staging) }, process.env.CERTBOT_BINARY || 'certbot')); }
  if (req.method === 'POST' && url.pathname === '/api/certificates/renew') return send(res, 200, { command: renewalCommand(process.env.CERTBOT_BINARY || 'certbot', process.env.KOTAUI_RENEW_HOOK || '') });
  if (req.method === 'POST' && url.pathname === '/api/traffic/sync') { const b = await readBody(req); const values = await collectUserTraffic(b.address || `127.0.0.1:${statsApiPort}`, state.clients.map(x => x.username)); for (const client of state.clients) { const item = values[client.username]; if (!item) continue; const previous = state.traffic[client.username]?.singbox || { uploadBytes: 0, downloadBytes: 0 }; const uploadDelta = Math.max(0, item.uploadBytes - previous.uploadBytes); const downloadDelta = Math.max(0, item.downloadBytes - previous.downloadBytes); ensureMonthlyReset(client, state.settings.timeZone || 'UTC'); applyTraffic(client, uploadDelta, downloadDelta, state.settings.timeZone || 'UTC'); state.traffic[client.username] = { ...(state.traffic[client.username] || {}), singbox: item, usedBytes: client.usedBytes, monthlyUsedBytes: client.monthlyUsedBytes, updatedAt: new Date().toISOString() }; } save(state); return send(res, 200, { ok: true, traffic: state.traffic }); }
  if (req.method === 'POST' && url.pathname === '/api/traffic/apply') { const b = await readBody(req); const client = state.clients.find(x => x.id === b.clientId || x.username === b.username); if (!client) return send(res, 404, { error: 'client not found' }); ensureMonthlyReset(client, state.settings.timeZone || 'UTC'); applyTraffic(client, b.uploadBytes, b.downloadBytes, state.settings.timeZone || 'UTC'); state.traffic[client.username] = { usedBytes: client.usedBytes, monthlyUsedBytes: client.monthlyUsedBytes, updatedAt: new Date().toISOString() }; save(state); return send(res, 200, { client, traffic: state.traffic[client.username] }); }
  if (req.method === 'POST' && url.pathname === '/api/traffic/online') { const b = await readBody(req); const client = state.clients.find(x => x.id === b.clientId || x.username === b.username); if (!client) return send(res, 404, { error: 'client not found' }); const current = state.traffic[client.username]?.activeIps || {}; const next = markActiveIp(current, b.ip); const decision = activeIpDecision(client, next); state.traffic[client.username] = { ...(state.traffic[client.username] || {}), activeIps: next, activeIpCount: decision.activeIps.length, lastOnlineCheck: new Date().toISOString() }; save(state); return send(res, decision.allowed ? 200 : 429, { ...decision, clientEnabled: client.enabled !== false }); }
  if (req.method === 'GET' && url.pathname === '/api/updates') return send(res, 200, { current: state.versions, available: { ui: '0.1.1', singBox: '1.14.1', hysteria2: '2.6.1' }, history: state.updateHistory.slice(0, 10) });
  if (req.method === 'POST' && url.pathname === '/api/updates/run') return send(res, 200, await runUpdate(await readBody(req)));
  if (req.method === 'POST' && url.pathname === '/api/config/validate') { rebuildConfig(); return send(res, 200, { configFile, ...validateConfig(configFile, process.env.SING_BOX_BINARY || 'sing-box') }); }
  if (req.method === 'POST' && url.pathname === '/api/inbounds') { const b = await readBody(req); const error = validateInbound(b); if (error) return send(res, 400, { error }); const item = { ...b, id: id(), name: String(b.name), port: Number(b.port), listen: b.listen || '0.0.0.0', enabled: b.enabled !== false, createdAt: new Date().toISOString() }; state.inbounds.push(item); rebuildConfig(); save(state); const firewall = openInboundPort(item.port, item.type === 'hysteria2' ? 'udp' : item.type === 'shadowsocks2022' ? item.network : 'tcp'); return send(res, 201, { ...item, privateKey: undefined, password: undefined, firewall }); }
  if (req.method === 'DELETE' && url.pathname.startsWith('/api/inbounds/')) { const iid = url.pathname.split('/').pop(); const removed = state.inbounds.find(x => x.id === iid); const before = state.inbounds.length; state.inbounds = state.inbounds.filter(x => x.id !== iid); if (before === state.inbounds.length) return send(res, 404, { error: 'inbound not found' }); state.clients.forEach(c => c.inbounds = c.inbounds.filter(x => x !== iid)); rebuildConfig(); save(state); const firewall = closeInboundPort(removed.port, removed.type === 'hysteria2' ? 'udp' : removed.type === 'shadowsocks2022' ? removed.network : 'tcp'); return send(res, 200, { ok: true, firewall }); }
  if (req.method === 'POST' && url.pathname === '/api/clients') { const b = await readBody(req); if (!validUsername(b.username)) return send(res, 400, { error: 'username must be 3-32 chars: A-Z, a-z, 0-9, _ or -' }); if (state.clients.some(c => c.username === b.username)) return send(res, 409, { error: 'username already exists' }); const item = { id: id(), username: b.username, note: b.note || '', inbounds: Array.isArray(b.inbounds) ? b.inbounds : [], totalLimitBytes: Number(b.totalLimitBytes || 0), monthlyLimitBytes: Number(b.monthlyLimitBytes || 0), expiresAt: b.expiresAt || null, maxOnlineIps: Number(b.maxOnlineIps || 0), enabled: true, usedBytes: 0, monthlyUsedBytes: 0, credentials: { reality: crypto.randomUUID(), hysteria2: crypto.randomBytes(18).toString('base64url'), shadowsocks2022: crypto.randomBytes(18).toString('base64url') }, createdAt: new Date().toISOString() }; state.clients.push(item); rebuildConfig(); save(state); return send(res, 201, { ...item, credentials: undefined }); }
  if (req.method === 'PATCH' && url.pathname.startsWith('/api/clients/')) { const cid = url.pathname.split('/').pop(); const item = state.clients.find(x => x.id === cid); if (!item) return send(res, 404, { error: 'client not found' }); const b = await readBody(req); if (b.username && (!validUsername(b.username) || state.clients.some(x => x.id !== cid && x.username === b.username))) return send(res, 400, { error: 'invalid or duplicate username' }); Object.assign(item, b); rebuildConfig(); save(state); return send(res, 200, { ...item, credentials: undefined }); }
  if (req.method === 'GET' && url.pathname.startsWith('/kota-sub/')) { const username = url.pathname.split('/').pop(); const client = state.clients.find(x => x.username === username); if (!client) return send(res, 404, { error: 'subscription not found' }, 'text/plain'); const nodes = state.inbounds.filter(x => client.inbounds.includes(x.id) && x.enabled).map(x => ({ tag: x.name, type: x.type, server: state.settings.domain || '127.0.0.1', server_port: x.port })); return send(res, 200, { username, updated_at: new Date().toISOString(), outbounds: nodes }, 'application/json'); }
  if (req.method === 'GET' && (url.pathname === '/' || url.pathname === '/index.html')) return send(res, 200, fs.readFileSync(path.join(root, 'public', 'index.html'), 'utf8'), 'text/html');
  return send(res, 404, { error: 'not found' });
};
const handler = (req, res) => routes(req, res).catch(err => send(res, 400, { error: err.message }));
const server = fs.existsSync(tlsCert) && fs.existsSync(tlsKey) ? https.createServer({ cert: fs.readFileSync(tlsCert), key: fs.readFileSync(tlsKey) }, handler) : http.createServer(handler);
server.listen(port, host, () => { try { rebuildConfig(); } catch (e) { console.error(`config initialization failed: ${e.message}`); } console.log(`KotaUI listening on http://${host}:${port}`); });
